### ISSUE TITLE
configuring `gci test` command params

### ISSUE THREAD

**Issue by bacongobbler** [arschles/gocons#36]
In some projects like deis/workflow-e2e, it uses a custom test command like `ginkgo --focus=Apps .` to only run tests related to a certain tag. Is there functionality built into gci to supply your own test command?

**Comment by arschles** [comment]
Nope, not yet. I'm thinking something like this to do so:

``` yaml
test:
  command: ginkgo --focus=Apps
```

The presence of `command` would mean that the default `go test` command would not be used. `gci` should error if this and `paths:` both exist in the file, since they don't make sense together.

**Comment by arschles** [comment]
Solved by https://github.com/arschles/gci/pull/76. Closing
